** Criação de banco de dados para um cenário de E-Commerce


CREATE DATABASE ECOMMERCE:


USE ECOMMERCE;


CREATE TABLE CLIENTES(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	P_NOME VARCHAR(10) NOT NULL,
	NOME_MEIO VARCHAR(3) NOT NULL,
	SOBRENOME VARCHAR(20) NOT NULL,
	CPF CHAR(11) NOT NULL,
	ENDEREÇO VARCHAR(45) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	CONSTRAINT UNIQUE_CPF_CLIENTE UNIQUE(CPF)
);


CREATE TABLE PRODUTOS(
	ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	N_PRODUTO VARCHAR(10) NOT NULL,
	CLASS_CRIANÇA BOOL DEFAULT FALSE,
	CATEGORIA ENUM('ELETRONICO','VESTUARIA','BRINQUEDOS','ALIMENTOS','MOVEIS') NOT NULL,
	AVALIAÇAO FLOAT DEFAULT 0,
	DIMENSOES VARCHAR(10)
);


CREATE TABLE PAGAMENTO(
	IDCLIENTE INT,
	ID_PAGAMENTO INT,
	TIPO_PAGAMENTO ENUM('BOLETO','CARTAO','DOIS_CARTOES'),
	LIMITE FLOAT,
	PRIMARY KEY (IDCLIENTE, ID_PAGAMENTO),
	CONTRAINT FK_CLIENTE_PAGAMENTO FOREIGN KEY (IDCLIENTE)
	REFERENCES CLIENTES (ID_CLIENTE)
);



CONSTRAINT FK_PEDIDO_PAGAMENTO FOREIGN KEY (IDPAGAMENTO)
	REFERENCES PAGAMENTO (ID_PAGAMENTO), 


CREATE TABLE PEDIDO(
	ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
	PEDIDO_CLIENTE INT,
	STATUS_PEDIDO ENUM('CANCELADO','CONFIRMADO','EM PROCESSAMENTO','ENVIADO') DEFAULT 'EM PROCESSAMENTO',
	DESCRIÇAO VARCHAR(255),
	FRETE FLOAT DEFAULT 10,
	PAGAMENTO_BOLETO BOOL DEFAULT FALSE,
	IDPAGAMENTO INT,
	CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (PEDIDO_CLIENTE)
	REFERENCES CLIENTES (ID_CLIENTE)
);


CREATE TABLE ESTOQUE(
	ID_ESTOQUE INT PRIMARY KEY AUTO_INCREMENT,
	LOCAL VARCHAR(255),
	QUANTIDADE INT DEFAULT 10
);


CREATE TABLE FORNECEDOR(
	ID_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
	RAZAO_SOCIAL VARCHAR(255) NOT NULL,
	CNPJ CHAR(14) NOT NULL,
	CONTATO CHAR(11) NOT NULL,
	CONSTRAINT CNPJ_FORNECEDOR UNIQUE (CNPJ)
);


CREATE TABLE VENDEDOR(
	ID_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	RAZAO_SOCIAL VARCHAR(45),
	NOME_FANTASIA VARCHAR(45),
	CNPJ CHAR(14) NOT NULL,
	CPF CHAR(11) NOT NULL,
	LOCALIDADE VARCHAR(255) NOT NULL,
	CONTATO CHAR(11) NOT NULL,
	CONSTRAINT CNPJ_VENDEDOR UNIQUE (CNPJ),
	CONSTRAINT CPF_VENDEDOR UNIQUE (CPF)
);


CREATE TABLE PRODUTO_VENDEDOR(
	ID_PROD_VENDEDOR INT,
	IDPRODUTO INT,
	QUANTIDADE INT DEFAULT 1,
	PRIMARY KEY (ID_PROD_VENDEDOR, IDPRODUTO),
	CONSTRAINT FK_PRODUTO_VENDEDOR FOREIGN KEY (ID_PROD_VENDEDOR)
	REFERENCES VENDEDOR (ID_VENDEDOR),
	CONSTRAINT FK_PRODUTO FOREIGN KEY (IDPRODUTO)
	REFERENCES PRODUTOS (ID_PRODUTO)
);


CREATE TABLE PEDIDO_PRODUTO(
	ID_PROD_PEDIDO INT,
	IDPEDIDO INT, 
	PROD_QTD INT DEFAULT 1,
	PROD_STATUS ENUM('DISPONIVEL','SEM ESTOQUE') DEFAULT 'DISPONIVEL',
	PRIMARY KEY (ID_PROD_PEDIDO, IDPEDIDO),
	CONSTRAINT FK_PEDIDO_VENDEDOR FOREIGN KEY (ID_PROD_PEDIDO)
	REFERENCES PRODUTOS (ID_PRODUTO),
	CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY (IDPEDIDO)
	REFERENCES PEDIDO (ID_PEDIDO)
);


CREATE TABLE PRODUTO_ESTOQUE(
	ID_PROD_ESTOQUE INT,
	IDESTOQUE INT, 
	LOCALIZAÇAO VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID_PROD_ESTOQUE, IDESTOQUE),
	CONSTRAINT FK_PRODUTO_ESTOQUE FOREIGN KEY (ID_PROD_ESTOQUE)
	REFERENCES PRODUTOS (ID_PRODUTO),
	CONSTRAINT FK_ESTOQUE_ESTOQUE FOREIGN KEY (IDESTOQUE)
	REFERENCES ESTOQUE (ID_ESTOQUE)
);


CREATE TABLE PRODUTO_FORNECEDOR(
	ID_PROD_FORNECEDOR INT,
	ID_FOR_PRODUTO INT,
	QUANTIDADE INT NOT NULL,
	PRIMARY KEY (ID_PROD_FORNECEDOR, ID_FOR_PRODUTO),
	CONSTRAINT FK_PRODUTO_FORNECEDOR FOREIGN KEY (ID_PROD_FORNECEDOR)
	REFERENCES FORNECEDOR (ID_FORNECEDOR),
	CONSTRAINT FK_PRODUTO_FORNECEDOR_PROD FOREIGN KEY (ID_FOR_PRODUTO)
	REFERENCES PRODUTOS (ID_PRODUTO)
);



